queue_rules:
  - name: default
    update_method: rebase
    merge_method: merge
    commit_message_template: |
      Merge pull request #{{ number }} from {{ head }}

      {{ title }}

      {% for commit in commits %}
      {{ commit.commit_message }}
      {% endfor %}
    queue_conditions:
      - check-success = "Coding Standards and PHPStan"
    merge_conditions:
      - check-success = continuous-integration/jenkins/pr-merge

merge_protections:
  - name: Dependabot - Minor/Patches
    if:
      - base = develop
      - author = dependabot[bot]
      - "#commits = 1"
      - or:
        - dependabot-update-type = "version-update:semver-patch"
        - dependabot-update-type = "version-update:semver-minor"
    success_conditions:
      - "#approved-reviews-by >= 1"

  - name: Default
    if:
      - base = develop
    success_conditions:
      - "#approved-reviews-by >= 2"
