queue_rules:
  # Order is important here.
  - name: dependabot
    batch_size: 10
    update_method: rebase
    queue_branch_merge_method: fast-forward
    merge_method: rebase
    batch_max_wait_time: 1 min
    commit_message_template: |
      Merge pull request #{{ number }} from {{ head }}

      {{ title }}

      {% for commit in commits %}
      {{ commit.commit_message }}
      {% endfor %}
    queue_conditions:
      - author = dependabot[bot]
      - "#commits = 1"
    merge_conditions:
      - check-success = "PHP 8.2"
      - check-success = "PHP 8.3"

  - name: default
    update_method: rebase
    commit_message_template: |
      Merge pull request #{{ number }} from {{ head }}

      {{ title }}
    queue_conditions: []
    merge_conditions:
      - check-success = "PHP 8.2"
      - check-success = "PHP 8.3"

merge_protections:
  - name: Dependabot Major Updates
    description: Test
    if:
      - base = main
      - dependabot-update-type = "version-update:semver-major"
    success_conditions:
      - or:
        - "#approved-reviews-by >= 2"
        - "approved-reviews-by = cs278"
  - name: Dependabot Minor Updates
    description: Test
    if:
      - base = main
      - dependabot-update-type = "version-update:semver-minor"
    success_conditions:
      - "#approved-reviews-by >= 1"
