queue_rules:
  - name: default
    update_method: rebase
    merge_method: merge
    commit_message_template: |
      Merge pull request #{{ number }} from {{ head }}

      {{ title }}

      {% for commit in commits %}
      {{ commit.commit_message }}
      {% endfor %}
    queue_conditions:
      - check-success = "PHP 8.2"
    merge_conditions:
      - check-success = "PHP 8.3"

merge_protections:
  - name: Dependabot
    if:
      - base = main
      - author = dependabot[bot]
    success_conditions:
      - or:
        - and:
          - "#commits = 1"
          - "#files <= 2"
          - or:
            - dependabot-update-type = "version-update:semver-patch"
            - dependabot-update-type = "version-update:semver-minor"
          - "#approved-reviews-by >= 1"
        - "#approved-reviews-by >= 2"

  - name: Default
    if:
      - base = main
      - author != dependabot[bot]
    success_conditions:
      - "#approved-reviews-by >= 2"
