queue_rules:
  # Order is important here.
  - name: default
    update_method: rebase
    queue_conditions:
      - author != dependabot[bot]
    merge_conditions:
      - check-success = build

  - name: dependabot
    batch_size: 10
    update_method: rebase
    batch_max_wait_time: 30 min
    queue_conditions:
      - author = dependabot[bot]
    merge_conditions:
      - check-success = build

merge_protections:
  - name: Dependabot Major Updates
    description: Test
    if:
      - base = main
      - dependabot-update-type = "version-update:semver-major"
    success_conditions:
      - or:
        - "#approved-reviews-by >= 2"
        - "approved-reviews-by = cs278"
  - name: Dependabot Minor Updates
    description: Test
    if:
      - base = main
      - dependabot-update-type = "version-update:semver-minor"
    success_conditions:
      - "#approved-reviews-by >= 1"
