queue_rules:
  # Order is important here.
  - name: default
    update_method: rebase
    queue_conditions:
      - author != dependabot[bot]

  - name: dependabot
    batch_size: 10
    update_method: rebase
    batch_max_wait_time: 30 min
    queue_conditions:
      - author = dependabot[bot]

merge_protections:
  - name: Do not merge outdated PRs
    description: Make sure PRs are almost up to date before merging
    if:
      - base = main
    success_conditions:
      - "#commits-behind = 0"
  - name: Dependabot Major Updates
    description: Test
    if:
      - base = main
      - dependabot-update-type = "version-update:semver-major"
    success_conditions:
      - "#approved-reviews-by >= 2"
  - name: Dependabot Minor Updates
    description: Test
    if:
      - base = main
      - dependabot-update-type = "version-update:semver-minor"
    success_conditions:
      - "#approved-reviews-by >= 1"
